default: 
  predictions: &default_prediction
    xpath:
      voting_expression: "//body/font[1]/table[8]/tr//tr"
  results: &default_result
    xpath:
      parties_expression: "//partido"
      votes_number_expression: "//votos/contabilizados/cantidad"
      invalid_votes_number_expression: "//votos/nulos/cantidad"
      no_votes_number_expression: "//votos/abstenciones/cantidad"
      blank_votes_number_expression: "//votos/blancos/cantidad"

predictions:  
  aragon:
    <<: *default_prediction
    name: Aragón
    url: http://www.cis.es/cis/opencms/-Archivos/Marginales/2680_2699/2687/e268700.html
  asturias:
    <<: *default_prediction
    name: Asturias
    url: http://www.cis.es/cis/opencms/-Archivos/Marginales/2680_2699/2688/e268800.html
  baleares:
    <<: *default_prediction
    name: Baleares
    url: http://www.cis.es/cis/opencms/-Archivos/Marginales/2680_2699/2689/e268900.html
  canarias:
    <<: *default_prediction
    name: Canarias
    url: http://www.cis.es/cis/opencms/-Archivos/Marginales/2680_2699/2690/e269000.html
  cantabria:
    <<: *default_prediction
    name: Cantabria
    url: http://www.cis.es/cis/opencms/-Archivos/Marginales/2680_2699/2691/e269100.html
  castilla-la-mancha:
    <<: *default_prediction
    name: Castilla-La Mancha
    url: http://www.cis.es/cis/opencms/-Archivos/Marginales/2680_2699/2692/e269200.html
  castilla-leon:
    <<: *default_prediction
    name: Castilla León
    url: http://www.cis.es/cis/opencms/-Archivos/Marginales/2680_2699/2693/e269300.html
  comunidad-valenciana:
    <<: *default_prediction
    name: Comunidad Valenciana
    url: http://www.cis.es/cis/opencms/-Archivos/Marginales/2680_2699/2694/e269400.html
  extremadura:
    <<: *default_prediction
    name: Extremadura
    url: http://www.cis.es/cis/opencms/-Archivos/Marginales/2680_2699/2695/e269500.html
  la-rioja:
    <<: *default_prediction
    name: La Rioja
    url: http://www.cis.es/cis/opencms/-Archivos/Marginales/2680_2699/2699/e269900.html
  madrid:
    <<: *default_prediction
    name: Madrid
    url: http://www.cis.es/cis/opencms/-Archivos/Marginales/2680_2699/2696/e269600.html
# En Murcia se tiene que hacer a mano, no se puede aplicar un xpath
#  murcia:
#    <<: *default_prediction
#    name: Murcia
#    url: http://www.cis.es/cis/opencms/-Archivos/Marginales/2680_2699/2697/e269700.htm
#    xpath:
#      voting_expression: "//body//table[8]/tr//tr"
  navarra:
    <<: *default_result
    name: Navarra
    url: http://www.cis.es/cis/opencms/-Archivos/Marginales/2680_2699/2698/e269800.html

results:  
  aragon:
    <<: *default_result
    name: Aragón
    url: "http://resultados.elpais.com/elecciones/2007/autonomicas/02/index.xml2"
  asturias:
    <<: *default_result
    name: Asturias
    url: "http://resultados.elpais.com/elecciones/2007/autonomicas/03/index.xml2"
  baleares:
    <<: *default_result
    name: Baleares
    url: "http://resultados.elpais.com/elecciones/2007/autonomicas/04/index.xml2"
  canarias:
    <<: *default_result
    name: Canarias
    url: "http://resultados.elpais.com/elecciones/2007/autonomicas/05/index.xml2"
  cantabria:
    <<: *default_result
    name: Cantabria
    url: "http://resultados.elpais.com/elecciones/2007/autonomicas/06/index.xml2"
  castilla-la-mancha:
    <<: *default_result
    name: Castilla-La Mancha
    url: "http://resultados.elpais.com/elecciones/2007/autonomicas/07/index.xml2"
  castilla-leon:
    <<: *default_result
    name: Castilla León
    url: "http://resultados.elpais.com/elecciones/2007/autonomicas/08/index.xml2"
  comunidad-valenciana:
    <<: *default_result
    name: Comunidad Valenciana
    url: "http://resultados.elpais.com/elecciones/2007/autonomicas/17/index.xml2"
  extremadura:
    <<: *default_result
    name: Extremadura
    url: "http://resultados.elpais.com/elecciones/2007/autonomicas/10/index.xml2"
  la-rioja:
    <<: *default_result
    name: La Rioja
    url: "http://resultados.elpais.com/elecciones/2007/autonomicas/16/index.xml2"
  madrid:
    <<: *default_result
    name: Madrid
    url: "http://resultados.elpais.com/elecciones/2007/autonomicas/12/index.xml2"
  murcia:
    <<: *default_result
    name: Murcia
    url: "http://resultados.elpais.com/elecciones/2007/autonomicas/15/index.xml2"
  navarra:
    <<: *default_result
    name: Navarra
    url: "http://resultados.elpais.com/elecciones/2007/autonomicas/13/index.xml2"

labels:
  parties:
    PP: PP
    UPN: PP
    PSOE: PSOE
    CIU: CIU
    PNV: PNV
  blank: ["En blanco", "No votaría"]
  no_label: ["No sabe todavía", "N.C.", "TOTAL"]
  